import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { useAdminDraft } from "@/components/admin/DraftContext";
import { cmsRepository } from "@/lib/cms";
import { uploadImage } from "@/lib/media";
import { confirmAction } from "@/lib/dialog";
import type { ImageSpec } from "@/lib/images";
import type { OfficeAddress, SiteConfig, SocialLink } from "@/types/site";

type Panel = "business" | "social" | "locations" | "footer";

const panels: Array<{ id: Panel; label: string; description: string }> = [
  { id: "business", label: "Business", description: "Name, logo and primary contact" },
  { id: "social", label: "Social media", description: "Visitor-facing profile links" },
  { id: "locations", label: "Locations", description: "Addresses and map directions" },
  { id: "footer", label: "Footer", description: "Labels, message and disclaimer" },
];

function Field({ label, value, onChange, area = false, type = "text", hint }: { label: string; value: string; onChange: (value: string) => void; area?: boolean; type?: string; hint?: string }) {
  return <label className="block"><span className="label-caps text-ink-500">{label}</span>{area ? <textarea rows={4} className="cms-input resize-y" value={value} onChange={(event) => onChange(event.target.value)} /> : <input type={type} className="cms-input" value={value} onChange={(event) => onChange(event.target.value)} />}{hint && <span className="mt-2 block text-xs leading-relaxed text-ink-400">{hint}</span>}</label>;
}

function LogoField({ image, onChange, notify }: { image: ImageSpec; onChange: (image: ImageSpec) => void; notify: (message: string) => void }) {
  const [uploading, setUploading] = useState(false);
  return <div className="rounded-xl border border-line bg-cream-100/60 p-5 sm:col-span-2"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><div className="flex aspect-video w-full max-w-56 items-center justify-center overflow-hidden rounded-lg border border-line bg-cream-50 p-5">{image.src ? <img src={image.src} alt="" className="max-h-full max-w-full object-contain" /> : <span className="text-sm text-ink-400">No logo</span>}</div><div><p className="label-caps text-ink-500">Business logo</p><p className="mt-2 text-xs leading-relaxed text-ink-500">Use a transparent PNG or WebP with generous space around the mark.</p><div className="mt-4 flex flex-wrap gap-3"><label className="cursor-pointer rounded-full bg-pine-800 px-4 py-2 text-xs font-semibold text-cream-50"><span>{uploading ? "Uploading…" : image.src ? "Replace logo" : "Upload logo"}</span><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={uploading} onChange={async (event) => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; setUploading(true); try { onChange({ ...image, src: await uploadImage(file) }); } catch (cause) { notify(cause instanceof Error ? cause.message : "Logo upload failed."); } finally { setUploading(false); } }} /></label>{image.src && <button type="button" className="text-xs font-semibold text-coral-700" onClick={() => onChange({ ...image, src: "" })}>Remove</button>}</div></div></div><div className="mt-5"><Field label="Logo alt text" value={image.alt} onChange={(alt) => onChange({ ...image, alt })} hint="Describe the logo for visitors using screen readers." /></div></div>;
}

function syncLegacySocial(config: SiteConfig): SiteConfig {
  const links = [...config.socialLinks].filter((item) => item.enabled).sort((a, b) => a.sortOrder - b.sortOrder);
  const facebook = links.filter((item) => item.platform === "facebook");
  return { ...config, social: {
    facebookCorporate: facebook[0]?.url ?? config.social.facebookCorporate,
    facebookResort: facebook[1]?.url ?? facebook[0]?.url ?? config.social.facebookResort,
    youtube: links.find((item) => item.platform === "youtube")?.url ?? config.social.youtube,
    instagram: links.find((item) => item.platform === "instagram")?.url ?? config.social.instagram,
  } };
}

export function SettingsEditor({ notify, initialPanel = "business" }: { notify: (message: string) => void; initialPanel?: Panel }) {
  const [config, setConfig] = useAdminDraft(() => cmsRepository.getSiteConfig());
  const [panel, setPanel] = useState<Panel>(initialPanel);
  const [saving, setSaving] = useState(false);
  const [draggedSocial, setDraggedSocial] = useState<number>();
  const logo = config.logo ?? { src: "", alt: "AFhomes" };
  const reset = () => setConfig(cmsRepository.getSiteConfig());
  const save = async () => {
    if (saving) return;
    setSaving(true);
    try { await cmsRepository.saveSiteConfig(syncLegacySocial(config)); notify("Settings updated successfully."); }
    catch (cause) { notify(cause instanceof Error ? `Settings update failed: ${cause.message}` : "Settings update failed."); }
    finally { setSaving(false); }
  };
  const updateOffice = (index: number, patch: Partial<OfficeAddress>) => setConfig((current) => ({ ...current, offices: current.offices.map((office, itemIndex) => itemIndex === index ? { ...office, ...patch } : office) }));
  const updateSocial = (id: string, patch: Partial<SocialLink>) => setConfig((current) => ({ ...current, socialLinks: current.socialLinks.map((item) => item.id === id ? { ...item, ...patch } : item) }));
  const reorderSocial = (from: number, to: number) => setConfig((current) => {
    if (from === to || from < 0 || to < 0 || from >= current.socialLinks.length || to >= current.socialLinks.length) return current;
    const links = [...current.socialLinks];
    const [moved] = links.splice(from, 1);
    links.splice(to, 0, moved);
    return { ...current, socialLinks: links.map((item, index) => ({ ...item, sortOrder: index })) };
  });
  return <section className="overflow-hidden rounded-2xl border border-line bg-cream-50 shadow-soft"><header className="border-b border-line px-5 py-6 sm:px-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="label-caps text-leaf-700">Site-wide content</p><h2 className="font-display mt-2 text-4xl font-medium text-navy-900">Settings</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-ink-600">Keep business identity, contact details, public links, navigation, and footer content accurate in one place.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={reset}>Cancel</Button><Button variant="outline" size="sm" onClick={() => window.open("/", "_blank", "noopener,noreferrer")}>View live site</Button><Button variant="accent" size="sm" disabled={saving} onClick={() => void save()}>{saving ? "Updating…" : "Update settings"}</Button></div></div></header><div className="border-b border-line bg-cream-100/60 px-4 py-3"><div className="flex gap-2 overflow-x-auto" role="tablist" aria-label="Settings sections">{panels.map((item) => <button key={item.id} type="button" role="tab" aria-selected={panel === item.id} title={item.description} onClick={() => setPanel(item.id)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${panel === item.id ? "bg-pine-800 text-cream-50" : "border border-line bg-cream-50 text-ink-600 hover:border-leaf-500"}`}>{item.label}</button>)}</div></div><div className="p-5 sm:p-8">
    {panel === "business" && <div className="grid gap-5 sm:grid-cols-2"><LogoField image={logo} onChange={(image) => setConfig({ ...config, logo: image })} notify={notify} /><div className="sm:col-span-2"><Field label="Legal business name" value={config.businessName} onChange={(businessName) => setConfig({ ...config, businessName })} /></div><Field label="Public brand name" value={config.brand.name} onChange={(name) => setConfig({ ...config, brand: { ...config.brand, name } })} /><Field label="Tagline" value={config.brand.tagline} onChange={(tagline) => setConfig({ ...config, brand: { ...config.brand, tagline } })} /><Field label="Main contact number" value={config.phoneDisplay} type="tel" onChange={(phoneDisplay) => setConfig({ ...config, phoneDisplay, phone: phoneDisplay.replace(/[^+\d]/g, "") })} hint="Visitors can tap this number to call." /><Field label="Main email" value={config.email} type="email" onChange={(email) => setConfig({ ...config, email })} hint="Visitors can tap this address to email AFhomes." /><div className="sm:col-span-2"><Field label="Brand mantra" value={config.brand.mantra} onChange={(mantra) => setConfig({ ...config, brand: { ...config.brand, mantra } })} /></div></div>}
    {panel === "social" && <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h3 className="font-display text-2xl text-navy-900">Social links</h3><p className="mt-1 text-sm text-ink-500">Only enabled links appear publicly. Drag cards or use the arrow buttons to reorder them.</p></div><Button size="sm" onClick={() => setConfig((current) => ({ ...current, socialLinks: [...current.socialLinks, { id: crypto.randomUUID(), label: "New social link", platform: "other", url: "https://", enabled: true, sortOrder: current.socialLinks.length }] }))}>+ Add social link</Button></div><div className="mt-6 space-y-4">{config.socialLinks.length === 0 && <div className="rounded-xl border border-dashed border-line p-8 text-center text-sm text-ink-500">No social links yet. Add one to help visitors find AFhomes online.</div>}{config.socialLinks.map((item, index) => <article key={item.id} draggable onDragStart={() => setDraggedSocial(index)} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (draggedSocial !== undefined) reorderSocial(draggedSocial, index); setDraggedSocial(undefined); }} className="rounded-xl border border-line bg-cream-100/50 p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="cursor-grab text-lg text-ink-400" aria-hidden="true">⋮⋮</span><label className="flex items-center gap-2 text-sm font-semibold text-pine-900"><input type="checkbox" checked={item.enabled} onChange={(event) => updateSocial(item.id, { enabled: event.target.checked })} /> Enabled</label></div><div className="flex gap-3 text-xs font-semibold"><button type="button" disabled={index === 0} onClick={() => reorderSocial(index, index - 1)}>↑ Up</button><button type="button" disabled={index === config.socialLinks.length - 1} onClick={() => reorderSocial(index, index + 1)}>↓ Down</button><button type="button" className="text-coral-700" onClick={async () => { if (await confirmAction("Remove social link?", `${item.label} will be removed after you update settings.`)) setConfig((current) => ({ ...current, socialLinks: current.socialLinks.filter((link) => link.id !== item.id).map((link, sortOrder) => ({ ...link, sortOrder })) })); }}>Remove</button></div></div><div className="grid gap-4 sm:grid-cols-[1fr_11rem_2fr]"><Field label="Visitor label" value={item.label} onChange={(label) => updateSocial(item.id, { label })} /><label><span className="label-caps text-ink-500">Platform</span><select className="cms-input" value={item.platform} onChange={(event) => updateSocial(item.id, { platform: event.target.value as SocialLink["platform"] })}><option value="facebook">Facebook</option><option value="instagram">Instagram</option><option value="youtube">YouTube</option><option value="other">Other</option></select></label><Field label="Secure profile URL" value={item.url} type="url" onChange={(url) => updateSocial(item.id, { url })} /></div></article>)}</div></div>}
    {panel === "locations" && <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h3 className="font-display text-2xl text-navy-900">Contact & locations</h3><p className="mt-1 text-sm text-ink-500">Addresses and directions appear in the public contact page and footer.</p></div><Button size="sm" onClick={() => setConfig((current) => ({ ...current, offices: [...current.offices, { name: "New location", role: "Location", lines: ["Address"], mapUrl: "https://" }] }))}>+ Add location</Button></div><div className="mt-6 space-y-5">{config.offices.map((office, index) => <article key={`${office.name}-${index}`} className="rounded-xl border border-line bg-cream-100/50 p-5"><div className="flex items-start justify-between gap-3"><h4 className="font-display text-xl text-navy-900">{office.name}</h4><button type="button" className="text-xs font-semibold text-coral-700" onClick={async () => { if (await confirmAction("Remove location?", `${office.name} will disappear from the public site after updating settings.`)) setConfig((current) => ({ ...current, offices: current.offices.filter((_, itemIndex) => itemIndex !== index) })); }}>Remove</button></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Location name" value={office.name} onChange={(name) => updateOffice(index, { name })} /><Field label="Location type" value={office.role} onChange={(role) => updateOffice(index, { role })} /><div className="sm:col-span-2"><Field label="Address lines · one per line" area value={office.lines.join("\n")} onChange={(value) => updateOffice(index, { lines: value.split("\n").map((line) => line.trim()).filter(Boolean) })} /></div><div className="sm:col-span-2"><Field label="Map URL" type="url" value={office.mapUrl ?? ""} onChange={(mapUrl) => updateOffice(index, { mapUrl })} /></div></div></article>)}</div></div>}
    {panel === "footer" && <div className="grid gap-5 sm:grid-cols-2"><Field label="Eyebrow" value={config.footerEyebrow} onChange={(footerEyebrow) => setConfig({ ...config, footerEyebrow })} /><Field label="Copyright line" value={config.footerCopyright} onChange={(footerCopyright) => setConfig({ ...config, footerCopyright })} /><div className="sm:col-span-2"><Field label="Footer headline" area value={config.footerTitle} onChange={(footerTitle) => setConfig({ ...config, footerTitle })} /></div><Field label="Explore column label" value={config.footerExploreLabel} onChange={(footerExploreLabel) => setConfig({ ...config, footerExploreLabel })} /><Field label="Experiences column label" value={config.footerExperiencesLabel} onChange={(footerExperiencesLabel) => setConfig({ ...config, footerExperiencesLabel })} /><Field label="Contact column label" value={config.footerContactLabel} onChange={(footerContactLabel) => setConfig({ ...config, footerContactLabel })} /><Field label="Offices column label" value={config.footerOfficesLabel} onChange={(footerOfficesLabel) => setConfig({ ...config, footerOfficesLabel })} /><Field label="Notice title" value={config.footerNoticeTitle} onChange={(footerNoticeTitle) => setConfig({ ...config, footerNoticeTitle })} /><div className="sm:col-span-2"><Field label="Notice body" area value={config.footerNoticeBody} onChange={(footerNoticeBody) => setConfig({ ...config, footerNoticeBody })} /></div></div>}
  </div></section>;
}
