import type { ImageSpec } from "@/lib/images";

export interface PageContent {
  home: {
    heroTitle: string;
    heroLede: string;
    heroBadge: string;
    heroPrimaryCta: string;
    heroSecondaryCta: string;
    brandTitle: string;
    brandLede: string;
    brandEyebrow: string;
    brandImage: ImageSpec;
    brandHighlights: Array<{ label: string; value: string }>;
    brandQuote: string;
    whyTitle: string;
    whyLede: string;
    whyPillars: Array<{ title: string; body: string }>;
    ecosystemEyebrow: string;
    ecosystemTitle: string;
    ecosystemLede: string;
    smartWellnessEyebrow: string;
    smartWellnessTitle: string;
    smartWellnessLede: string;
    smartWellnessRooms: Array<{ value: string; label: string }>;
    smartWellnessStatus: string;
    smartWellnessButton: string;
    smartWellnessFeatures: Array<{ title: string; line: string }>;
    almEyebrow: string;
    almTitle: string;
    almLede: string;
    almStatus: string;
    almBadge: string;
    almButton: string;
    almFeatures: Array<{ label: string; note: string }>;
    almImageNote: string;
    hotspringEyebrow: string;
    hotspringTitle: string;
    hotspringLede: string;
    hotspringStats: Array<{ value: number; label: string; suffix?: string }>;
    hotspringFeatures: string[];
    hotspringStatus: string;
    hotspringButton: string;
    journeyEyebrow: string;
    journeyTitle: string;
    journeyLede: string;
    journeyMilestones: Array<{ phase: string; name: string; note: string; ghost: string; accent: string; ring: string; text: string; line: string }>;
    vipTeaserEyebrow: string;
    vipTeaserTitle: string;
    vipTeaserLede: string;
    vipTeaserButton: string;
    ctaEyebrow: string;
    ctaTitle: string;
    ctaLede: string;
    ctaPrimaryCta: string;
    ctaSecondaryCta: string;
  };
  about: {
    eyebrow: string;
    title: string;
    lede: string;
    image: ImageSpec;
    vision: string;
    mission: string;
    introEyebrow: string;
    introTitle: string;
    introLede: string;
    philosophyTitle: string;
    philosophyBody: string;
    stats: Array<{ value: string; label: string }>;
    modelEyebrow: string;
    modelTitle: string;
    modelLede: string;
    modelBody: string;
    modelChapters: Array<{ number: string; title: string; body: string }>;
    operationsEyebrow: string;
    operationsTitle: string;
    operationsCallout: string;
    operationsTitleSecondary: string;
    operationsLede: string;
    familyHeading: string;
    familyLede: string;
    familyButton: string;
  };
  compliance: {
    eyebrow: string;
    title: string;
    lede: string;
    commitmentTitle: string;
    commitmentLede: string;
    notInvestment: string;
    verifiedPayments: string;
    privacy: string;
    terms: string;
  };
  faq: {
    eyebrow: string;
    title: string;
    lede: string;
    browseTitle: string;
    contactPrompt: string;
    stillCuriousTitle: string;
    stillCuriousLede: string;
    stillCuriousButton: string;
  };
  contact: {
    eyebrow: string;
    title: string;
    lede: string;
    emailLabel: string;
    phoneLabel: string;
    formTitle: string;
    formLede: string;
    quickAnswerTitle: string;
    quickAnswerLede: string;
    quickAnswerButton: string;
  };
  experiences: {
    eyebrow: string;
    title: string;
    lede: string;
    image: ImageSpec;
  };
  vip: {
    eyebrow: string;
    title: string;
    lede: string;
    tierEyebrow: string;
    tierTitle: string;
    tierLede: string;
    steps: Array<{ number: string; title: string; body: string }>;
    includedEyebrow: string;
    includedTitle: string;
    includedLede: string;
    includedButton: string;
    includedItems: Array<{ title: string; body: string }>;
    transparencyEyebrow: string;
    transparencyTitle: string;
    transparencyLede: string;
    transparencyButton: string;
    transparencyCards: Array<{ title: string; body: string }>;
  };
  stories: {
    eyebrow: string;
    title: string;
    lede: string;
    image: ImageSpec;
  };
}
