import { Button } from "@/components/ui/Button";
import { Container } from "@/components/ui/Container";
import { SmartImage } from "@/components/ui/SmartImage";
import type { CmsPageSection } from "@/types/pageBuilder";

const text = (content: Record<string, unknown>, key: string) => typeof content[key] === "string" ? content[key] : "";
const items = (content: Record<string, unknown>) => Array.isArray(content.items) ? content.items.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object")) : [];

export function BlockRenderer({ section }: { section: CmsPageSection }) {
  const c = section.content;
  if (section.block_type === "divider") return <div className={text(c, "size") === "large" ? "h-28" : text(c, "size") === "small" ? "h-8" : "h-16"} aria-hidden="true" />;
  if (section.block_type === "hero") return <section className="relative flex min-h-[65svh] items-end overflow-hidden bg-navy-950 text-cream-50">{text(c, "mediaUrl") && (text(c, "mediaType") === "video" ? <video src={text(c, "mediaUrl")} autoPlay muted loop playsInline className="absolute inset-0 h-full w-full object-cover" /> : <SmartImage spec={{ src: text(c, "mediaUrl"), alt: "" }} className="absolute inset-0 h-full w-full object-cover" />)}<div className="absolute inset-0 bg-gradient-to-t from-navy-950 via-navy-950/60 to-transparent" /><Container className="relative z-10 pb-20 pt-36"><p className="label-caps text-leaf-300">{text(c, "eyebrow")}</p><h1 className="text-display mt-5 max-w-4xl text-cream-50">{text(c, "title")}</h1><p className="mt-6 max-w-2xl text-lg text-cream-200">{text(c, "text")}</p>{text(c, "buttonLabel") && <Button to={text(c, "buttonHref") || "/contact"} variant="accent" className="mt-8">{text(c, "buttonLabel")}</Button>}</Container></section>;
  if (section.block_type === "image") return <section className="bg-cream-100 py-12"><Container>{text(c, "url") && <figure><SmartImage spec={{ src: text(c, "url"), alt: text(c, "alt") }} className={`max-h-[80svh] w-full ${text(c, "fit") === "contain" ? "object-contain" : "object-cover"}`} />{text(c, "caption") && <figcaption className="mt-3 text-sm text-ink-500">{text(c, "caption")}</figcaption>}</figure>}</Container></section>;
  if (section.block_type === "video") return <section className="bg-cream-100 py-12"><Container>{text(c, "url") && <video src={text(c, "url")} controls={!c.autoplay} autoPlay={Boolean(c.autoplay)} muted={Boolean(c.autoplay)} loop={Boolean(c.loop)} playsInline preload="metadata" className="max-h-[80svh] w-full" />}{text(c, "caption") && <p className="mt-3 text-sm text-ink-500">{text(c, "caption")}</p>}</Container></section>;
  if (section.block_type === "two-column") return <section className="bg-cream-50 py-20"><Container className="grid items-center gap-10 md:grid-cols-2"><div className={text(c, "imageSide") === "left" ? "md:order-2" : ""}><h2 className="font-display text-4xl text-navy-900">{text(c, "heading")}</h2><p className="mt-5 whitespace-pre-line leading-relaxed text-ink-600">{text(c, "body")}</p></div>{text(c, "imageUrl") && <SmartImage spec={{ src: text(c, "imageUrl"), alt: text(c, "imageAlt") }} className="aspect-4/3 w-full object-cover" />}</Container></section>;
  if (["features", "services", "testimonials", "faq", "gallery"].includes(section.block_type)) return <section className="bg-cream-100 py-20"><Container><h2 className="font-display text-4xl text-navy-900">{text(c, "heading")}</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{items(c).map((item, index) => <article key={index} className="border border-line bg-cream-50 p-6">{typeof item.url === "string" && item.url && <SmartImage spec={{ src: item.url, alt: String(item.alt ?? "") }} className="mb-5 aspect-4/3 w-full object-cover" />}<h3 className="font-display text-2xl text-navy-900">{String(item.title ?? item.question ?? item.name ?? "")}</h3><p className="mt-3 whitespace-pre-line text-ink-600">{String(item.text ?? item.answer ?? item.quote ?? "")}</p></article>)}</div></Container></section>;
  if (section.block_type === "cta") return <section className="bg-pine-900 py-20 text-cream-50"><Container><h2 className="font-display text-4xl">{text(c, "heading")}</h2><p className="mt-4 max-w-2xl text-cream-200">{text(c, "text")}</p><Button to={text(c, "buttonHref") || "/contact"} variant="accent" className="mt-7">{text(c, "buttonLabel")}</Button></Container></section>;
  if (section.block_type === "contact") return <section className="bg-cream-50 py-20"><Container><h2 className="font-display text-4xl text-navy-900">{text(c, "heading")}</h2><p className="mt-4 text-ink-600">{text(c, "text")}</p><div className="mt-5 space-y-2"><p>{text(c, "email")}</p><p>{text(c, "phone")}</p></div></Container></section>;
  if (section.block_type === "map") return <section className="bg-cream-100 py-16"><Container><h2 className="font-display mb-7 text-4xl text-navy-900">{text(c, "heading")}</h2>{text(c, "embedUrl") && <iframe title={text(c, "heading") || "Map"} src={text(c, "embedUrl")} loading="lazy" className="h-96 w-full border-0" />}</Container></section>;
  return <section className="bg-cream-50 py-20"><Container size="narrow"><h2 className="font-display text-4xl text-navy-900">{text(c, "heading")}</h2><p className="mt-6 whitespace-pre-line leading-relaxed text-ink-600">{text(c, "body")}</p></Container></section>;
}
